/*
 COPYRIGHT 2010 ESRI
 
 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.
 
 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA
 
 email: contracts@esri.com
 */

#import <Foundation/Foundation.h>

/** @file AGSCredential.h */ //Required for Globals API doc

/** Supported authentication types.
 @since 1.0
 */
typedef enum {
	AGSAuthenticationTypeUnknown = 0,	/*!<  */
    AGSAuthenticationTypeNone,			/*!<  */
    AGSAuthenticationTypeToken,			/*!<  */
	AGSAuthenticationTypeHTTP,			/*!<  */
} AGSAuthenticationType;

/** @brief Represents an credential to access a secured resource.
 
 Instances of this class represent a credential object to access a secured ArcGIS resource. The
 resource could be secured using ArcGIS tokens or HTTP (basic or digest) authentication.
 
 @define{AGSCredential.h, ArcGIS}
 @since 1.0
 */
@interface AGSCredential : NSObject <NSCopying> {
 @private
	NSString *_username;
	NSString *_password;
	NSURL *_tokenUrl;
	AGSAuthenticationType _authType;
	NSString *_token;
    NSString *_referer;
	
	NSError *_setupError;
	BOOL _isSetup;
	NSInvocationOperation *_settingUpOperation;
    
    BOOL _sslRequired;
    NSURL *_setupURL;
}

/** Username used to access secured resource or retrieve a token.
 @since 1.0
 */
@property (nonatomic, retain) NSString *username;

/** Password used to access secured resource or retrieve a token.
 @since 1.0
 */
@property (nonatomic, retain) NSString *password;

/** Url to the token service.
 @since 1.0
 */
@property (nonatomic, copy) NSURL *tokenUrl;

/** The type of authentication needed to access a secured resource. Possibile
 values include
 
 @li @c AGSAuthenticationTypeUnknown
 @li @c AGSAuthenticationTypeNone
 @li @c AGSAuthenticationTypeToken
 @li @c AGSAuthenticationTypeHTTP	

 @since 1.0
 */
@property (nonatomic, assign) AGSAuthenticationType authType;

/** A string representing the referer for which the long-lived token was generated.
 @since 1.8
 */
@property (nonatomic, retain, readonly) NSString *referer;


/** Generated by the server from a username/password combination.
 @since 1.0
 */
@property (nonatomic, retain) NSString *token;

/** Indicates if the token provider requires that this token should only be transmitted over HTTPS.
 @since 2.2
 */
@property (nonatomic, assign, readonly) BOOL sslRequired;

/** Initialize an <code>%AGSCredential</code> object.
 @param username The username of user attempting to access secured resource.
 @param password The password of user attempting to access secured resource.
 @return A new, initialized <code>%AGSCredential</code>.
 @since 1.0
 */
- (id)initWithUser:(NSString*)username password:(NSString*)password;

/** Initialize an AGSCredential object when you know the authType.
 @param username The username of user attempting to access secured resource.
 @param password The passwordof user attempting to access secured resource.
 @param authType The authentication type to be used when accessing secured resource.
 @return A new, initialized <code>%AGSCredential</code>.
 @since 1.0
 */
- (id)initWithUser:(NSString*)username password:(NSString*)password authenticationType:(AGSAuthenticationType)authType;

/** Initialize an AGSCredential object when you know the #authType and #tokenUrl.
 @param username The username of user attempting to access secured resource.
 @param password The password of user attempting to access secured resource.
 @param authType The authentication type to be used when accessing secured resource.
 @param tokenUrl The token service URL to be used to retrieve a token with given 
 credentials.
 @return A new, initialized <code>%AGSCredential</code>.
 @since 1.0
 */
- (id)initWithUser:(NSString*)username password:(NSString*)password authenticationType:(AGSAuthenticationType)authType tokenUrl:(NSURL*)tokenUrl;

/** Initialize an AGSCredential object with a short-lived token. This token will be used to access the secured resource.
 @param token The short-lived token to initialize the credential object.
 @return A new, initialized <code>%AGSCredential</code>.
 @since 1.8
 */
- (id)initWithToken:(NSString*)token;

/** Initialize an AGSCredential object with a long-lived token and referer. This token will be used to access the secured resource.
 @param token The long-lived token to initialize the credential object.
 @param referer The referer to be sent along with token in the request.
 @return A new, initialized <code>%AGSCredential</code>.
 @since 1.8
 */
- (id)initWithToken:(NSString*)token referer:(NSString*)referer;

/** Helper method to deduce the URL for a token service. 
 @param url URL of the resource you wish to access.
 @return The URL of the token service.
 @since 1.0
 @deprecated Deprecated at 2.1. Please use getTokenServiceUrl:error: instead.
 */
+ (NSURL*)getTokenServiceUrl:(NSURL *)url __attribute__((deprecated));

/** Helper method to deduce the URL for a token service. 
 @param url URL of the resource you wish to access.
 @param error Returned if an error is encountered retrieving the token service url.
 @return The URL of the token service.
 @since 2.1
 */
+ (NSURL*)getTokenServiceUrl:(NSURL *)url error:(NSError**)error;

/** Determines the type of security, if any, of a resource with a given url.
 @param url URL of the resource you wish to access.
 @return The authentication type needed to access the specified resource.
 @since 1.0
 @deprecated Deprecated at 2.1. Please use isServiceSecured:error: instead.
 */
+ (AGSAuthenticationType)isServiceSecured:(NSURL*)url __attribute__((deprecated));

/** Determines the type of security, if any, of a resource with a given url.
 @param url URL of the resource you wish to access.
 @param error Returned if an error is encountered while determining if the service is secured.
 @return The authentication type needed to access the specified resource.
 @since 2.1
 */
+ (AGSAuthenticationType)isServiceSecured:(NSURL*)url error:(NSError**)error;

@end

/** @brief A protocol to aid in handling of secured resources.
 
 A protocol which must be adopted by a class wishing to handle token-expiration for a 
 particular resource. 
 
 @define{AGSCredential.h, ArcGIS}
 @since 1.0
 */
@protocol AGSSecuredResource <NSObject>

/** The credential to be used to access secured resources.
 @since 1.0
 */
@property (nonatomic, copy, readonly) AGSCredential *credential;

@end
